# Change these first
owner: sekondary # Your GitHub organization or username, where this repository lives
repo: voiceb-status-page # The name of this repository

sites:
  - name: Web
    url: https://www.voiceb.ai
  - name: App
    url: https://app.voiceb.ai
assignees:
  - lmdpsc
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voiceb.ai
  # baseUrl: /your-repo-name
  favicon: https://www.voiceb.ai/lovable-uploads/97d01dde-32ea-48d7-b0b5-3d64a44c297b.png
  name: VoiceB
  introTitle: ""
  introMessage: ""
  theme: night
  logoUrl: https://www.voiceb.ai/lovable-uploads/5c17062a-7451-4cc7-81be-f0b18b6e5e25.png
  navbar:
    - title: Status
      href: /
    - title: VoiceB
      href: https://www.voiceb.ai
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
